export const cardsData = [
  {
    id: 1,
    title: "33 слова о дизайне",
    url: "cards/1.png",
    duration: "1ч42м",
    isShortFilm: true,
  },
  {
    id: 2,
    title: "33 слова о дизайне",
    url: "cards/2.png",
    duration: "1ч42м",
    isShortFilm: false,
  },
  {
    id: 3,
    title: "33 слова о дизайне",
    url: "cards/3.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 4,
    title: "33 слова о дизайне",
    url: "cards/4.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 5,
    title: "33 слова о дизайне",
    url: "cards/5.png",
    duration: 102,
    isShortFilm: true,
  },
  {
    id: 6,
    title: "33 слова о дизайне",
    url: "cards/6.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 7,
    title: "33 слова о дизайне",
    url: "cards/7.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 8,
    title: "33 слова о дизайне",
    url: "cards/8.png",
    duration: 102,
    isShortFilm: true,
  },
  {
    id: 9,
    title: "33 слова о дизайне",
    url: "cards/9.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 10,
    title: "33 слова о дизайне",
    url: "cards/10.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 11,
    title: "33 слова о дизайне",
    url: "cards/11.png",
    duration: 102,
    isShortFilm: true,
  },
  {
    id: 12,
    title: "33 слова о дизайне",
    url: "cards/12.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 13,
    title: "33 слова о дизайне",
    url: "cards/13.png",
    duration: 102,
    isShortFilm: true,
  },
  {
    id: 14,
    title: "33 слова о дизайне",
    url: "cards/14.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 15,
    title: "33 слова о дизайне",
    url: "cards/15.png",
    duration: 102,
    isShortFilm: false,
  },
  {
    id: 16,
    title: "33 слова о дизайне",
    url: "cards/16.png",
    duration: 102,
    isShortFilm: true,
  },
];
