export const cardsData = [
  {
    card_id: 1,
    title: "33 слова о дизайне",
    url: "cards/1.jpg",
    duration: "1ч42м",
    isShortFilm: true,
  },
  {
    card_id: 2,
    title: "33 слова о дизайне",
    url: "cards/2.jpg",
    duration: "1ч42м",
    isShortFilm: false,
  },
  {
    card_id: 3,
    title: "33 слова о дизайне",
    url: "cards/3.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 4,
    title: "33 слова о дизайне",
    url: "cards/4.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 5,
    title: "33 слова о дизайне",
    url: "cards/5.jpg",
    duration: 102,
    isShortFilm: true,
  },
  {
    card_id: 6,
    title: "33 слова о дизайне",
    url: "cards/6.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 7,
    title: "33 слова о дизайне",
    url: "cards/7.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 8,
    title: "33 слова о дизайне",
    url: "cards/8.jpg",
    duration: 102,
    isShortFilm: true,
  },
  {
    card_id: 9,
    title: "33 слова о дизайне",
    url: "cards/9.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 10,
    title: "33 слова о дизайне",
    url: "cards/10.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 11,
    title: "33 слова о дизайне",
    url: "cards/11.jpg",
    duration: 102,
    isShortFilm: true,
  },
  {
    card_id: 12,
    title: "33 слова о дизайне",
    url: "cards/12.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 13,
    title: "33 слова о дизайне",
    url: "cards/13.jpg",
    duration: 102,
    isShortFilm: true,
  },
  {
    card_id: 14,
    title: "33 слова о дизайне",
    url: "cards/14.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 15,
    title: "33 слова о дизайне",
    url: "cards/15.jpg",
    duration: 102,
    isShortFilm: false,
  },
  {
    card_id: 16,
    title: "33 слова о дизайне",
    url: "cards/16.jpg",
    duration: 102,
    isShortFilm: true,
  },
];
